### ISSUE TITLE
Not overriding symlink at release-registry when publishing

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/craft#118]
When the [release-registry](https://github.com/getsentry/sentry-release-registry) already contains a symlink for the specified version craft fails to publish the release. I would expect that it overrides the symlink with the JSON for the specified release.

Steps to reproduce with sentry-cocoa:
1. `craft prepare 5.1.10`
2. Create a symlink for 5.1.10.json in [release-registry for cocoa](https://github.com/getsentry/sentry-release-registry/tree/master/packages/cocoapods/sentry-cocoa).
3. `craft publish 5.1.10 --target registry`
4. Craft fails with `Error: Version file for "5.1.10" already exists. Aborting.`
<img width="878" alt="Screenshot 2020-07-22 at 13 41 12" src="https://user-images.githubusercontent.com/2443292/88179088-a610cb80-cc2b-11ea-962a-cbf1ad02b1a1.png">

This is related to https://github.com/getsentry/sentry-release-registry/issues/27

**Comment by tonyo** [comment]
As mentioned in the offline discussion, this in not something we should change in craft, I believe. This error actually helped to uncover the issue we have with the tooling in release-registry.
@philipphofmann lmk if you still think that we should change this behavior.
