### ISSUE TITLE
Always print the version and force updates

### ISSUE THREAD

**Issue by jan-auer** [getsentry/craft#2]
Craft should always print its version on the top to make debugging easier. This way, developers can easily see if someone is running an outdated version of the package. I'm thinking similar to yarn:

```
$ yarn info
yarn info v1.9.4
```

Also, we should check for updates and inform the user. The package [update-nagger](https://github.com/yeoman/update-notifier) implements this functionality with nice visuals.

**Comment by tonyo** [comment]
Thanks for the suggestion, added in d969bdf7be01ec3622111b733a99ad6a9425c34b
