### ISSUE TITLE
craft publish: Ctrl-C handling is broken 

### ISSUE THREAD

**Issue by tonyo** [getsentry/craft#21]

**Comment by untitaker** [comment]
@tonyo just ran into this (Ctrl-C somehow orphans the process and I see both my shell prompt and craft output). Do you have an idea what the fix here is?

**Comment by tonyo** [comment]
In 0.7.10 this "feature" is disabled by default, I'll check what's wrong later.

**Comment by antonpirker** [comment]
Very old issue, and craft is mostly run in CI, so I will close this.
