### ISSUE TITLE
Allow "none" target with other targets

### ISSUE THREAD

**Issue by jan-auer** [getsentry/craft#25]
Can we remove `.None` from this list? It's quite convenient to "finish" an interrupted release with `-t <missing> -t none`. Maybe we should just rename it to `-t merge`.

https://github.com/getsentry/craft/blob/73947ac125c75ff73a780aab8bd0c7095e51c84e/src/commands/publish.ts#L577

**Comment by jan-auer** [comment]
Related to #7

**Comment by BYK** [comment]
Why is `-t <missing>` not enough for these cases?

**Comment by jan-auer** [comment]
This has to do with how craft finalizes publishing. Usually, the order is:
1. Run all targets
2. Finalize publishing, most notably merge the branch

However, we can also run a single target without finalizing. For instance, I can run just publish a crate: `craft publish 1.0.0 -t crates`. This doesn't finalize because one might want to run other targets. To wrap this up in the end, I need to run `craft publish -t none`, which doesn't run any targets and just finalizes.

Maybe this deserves a better, more explicit API. Something like:
```
craft publish 1.0.0 -t crates --finish
```

This could also work with no targets, in which case it could still be `-t none --finish`.

**Comment by BYK** [comment]
I think this will be important in our work towards making Craft more idempotent.

**Comment by BYK** [comment]
I think this is addressed via #192 and #197 so closing.
