### ISSUE TITLE
Support Public API files for .NET projects

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/craft#26]
.NET has a Roslyn Analyzer called [PublicApiAnalyzer](https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzers/).
This analyzer was added to the .NET project [via this pr](https://github.com/getsentry/sentry-dotnet/pull/234).

It works by raising compiler error if a public API is added/removed without adding it to controlling files.
There are two files:

`PublicAPI.Shipped.txt` and `PublicAPI.Unshipped.txt`
Which means that there's a new step when publishing NuGet packages. We must move the lines from the unshipped file to the shipped file. This should happen only when deploying non preview packages.

**Comment by BYK** [comment]
@bruno-garcia is this still relevant?
