### ISSUE TITLE
Improve logging for the Maven target

### ISSUE THREAD

**Issue by marandaneto** [getsentry/craft#272]
log the output of the maven CLI and gradlew CLI calls if `--log-level=debug` is enabled, so we can debug things if something goes wrong.

Craft also writes a file (~/.gradle/gradle.properties) with the exported env. vars `OSSRH_USERNAME` and `OSSRH_PASSWORD` values, required by Gradle, I suggest erasing these values (`mavenCentralUsername` and `mavenCentralPassword`) after Craft is executed, so we don't leak the user and pass.

there are also a few comments on https://github.com/getsentry/craft/pull/271

**Comment by iker-barriocanal** [comment]
Logging has been improved on https://github.com/getsentry/craft/pull/275 and `~/.gradle/gradle.properties` is removed since https://github.com/getsentry/craft/pull/276.
