### ISSUE TITLE
Handle remote checksum edge cases

### ISSUE THREAD

**Issue by iker-barriocanal** [getsentry/craft#322]
The GitHub target makes some assumptions to check whether the local and the remote checksums of an asset match, but the code doesn't handle when these assumptions aren't correct. See https://github.com/getsentry/craft/blob/e4f9962a309557aa975d559dc0ce497ca8dca1dc/src/targets/github.ts#L381-L407

Update: The `ETag` header isn't always present in the response, and this is making all releases using the `github` target to fail ([example](https://github.com/getsentry/publish/runs/4091096732?check_suite_focus=true#step:8:536)).

**Comment by BYK** [comment]
What are the assumptions? If we cannot get a checksum we should assume there's an error or retry?

**Comment by iker-barriocanal** [comment]
The assumptions are these in lines 382-385. I don't know what the behavior should be since I don't know why exactly it's happening, but if retrying helps to reduce that error, it's a strong alternative. One of the assumptions is we get the hash in the header, so if we don't we probably want to error, yes.

It seems this has happened again in [this release](https://github.com/getsentry/publish/issues/633), [see error](https://github.com/getsentry/publish/runs/4112277555?check_suite_focus=true#step:8:231).

**Comment by iker-barriocanal** [comment]
Update: The `ETag` header isn't always present in the response, and this is making all releases using the `github` target to fail.

A potential solution is to download the assets when `ETag` isn't in the headers and check the hash locally.

**Comment by chadwhitacre** [comment]
I'm seeing [an AWS facility for providing a hash](https://aws.amazon.com/premiumsupport/knowledge-center/data-integrity-s3/) when uploading, but we aren't uploading directly, GitHub is doing it for us. Looks like there's another lurking bug in that [files over 5GB have their `ETag` computed differently](https://coderedirect.com/questions/112270/what-is-the-algorithm-to-compute-the-amazon-s3-etag-for-a-file-larger-than-5gb). I'm also finding this caveat [under `ETag` on Common Response Headers](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html):

> The ETag may or may not be an MD5 digest of the object data. Whether or not it is depends on how the object was created and how it is encrypted as described below:
>
> - Objects created through the AWS Management Console or by the PUT Object, POST Object, or Copy operation:
>   - Objects encrypted by SSE-S3 or plaintext have ETags that are an MD5 digest of their data.
>   - Objects encrypted by SSE-C or SSE-KMS have ETags that are not an MD5 digest of their object data.
> - Objects created by either the Multipart Upload or Part Copy operation have ETags that are not MD5 digests, regardless of the method of encryption.

Here's [a slightly old Python implementation of this algorithm](https://teppen.io/2018/10/23/aws_s3_verify_etags/).

> The `ETag` header isn't always present in the response, and this is making all releases using the `github` target to fail.

Making _all_ releases to fail, or just those without an `ETag`?

Which response is the `ETag` not present in? We are depending on a redirect from GitHub:

https://github.com/getsentry/craft/blob/e4f9962a309557aa975d559dc0ce497ca8dca1dc/src/targets/github.ts#L381-L385

Are we sure that GitHub is issuing the redirect as expected? I would be somewhat surprised if AWS sometimes includes and ETag and sometimes doesn't. My hunch is that it is the redirect from GitHub that is breaking. Can we turn on trace logging to verify?

https://github.com/getsentry/craft/blob/e4f9962a309557aa975d559dc0ce497ca8dca1dc/src/targets/github.ts#L403

**Comment by chadwhitacre** [comment]
I kicked out a quick workaround in #323 to get us unblocked, since SDK deployments are getting back up behind this issue. Thoughts?

**Comment by marandaneto** [comment]
this still happens on https://github.com/getsentry/craft/releases/tag/0.27.2 sometimes, retrying works tho, but it's flaky.

**Comment by iker-barriocanal** [comment]
@marandaneto, could you link to a release that failed for this reason? I've only seen [sentry-unity `v0.7.0`](https://github.com/getsentry/publish/issues/671) failing since craft `v0.27.2`, and it doesn't look like it's this issue (it's probably github?).

**Comment by marandaneto** [comment]
> @marandaneto, could you link to a release that failed for this reason? I've only seen [sentry-unity `v0.7.0`](https://github.com/getsentry/publish/issues/671) failing since craft `v0.27.2`, and it doesn't look like it's this issue (it's probably github?).

this happened a few times using craft locally, with the maven target, so unfortunately no logs right now, @romtsn also experienced it.

**Comment by romtsn** [comment]
I think 0.27.2 fixed this for me
