### ISSUE TITLE
Improve GitHub asset upload retry algorithm

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/craft#337]
Seen a few times now that we can get an [intermittent asset upload failure](https://github.com/getsentry/self-hosted/issues/1193#issuecomment-995232447) from GitHub. Do we have a retry already for that? How about it?

@rhcarvalho @iker-barriocanal Do you recall the retry conversation we had earlier? Was it around GitHub asset uploads?

**Comment by BYK** [comment]
We try up to 3 times: https://github.com/getsentry/craft/blob/03fda08404939fb2a88c5059e1e5634689ea1cf1/src/targets/github.ts#L389

We can probably increase it and also add some delay?

**Comment by iker-barriocanal** [comment]
@chadwhitacre it was about [asset downloads](https://github.com/getsentry/craft/pull/328#discussion_r750417485).

**Comment by rhcarvalho** [comment]
Looking at the code at https://github.com/getsentry/craft/blob/03fda08404939fb2a88c5059e1e5634689ea1cf1/src/targets/github.ts#L394-L396, I am not sure if the retry logic is working as expected. @chadwhitacre's https://github.com/getsentry/publish/runs/4540082749?check_suite_focus=true#step:8:169 did have 3x 500 requests to the failed asset, but I don't see a "Reached maximum retries..." error.

![image](https://user-images.githubusercontent.com/88819/146371836-f5ad893c-2dd6-4cc4-9df4-c153ebd9252b.png)

We need https://github.com/getsentry/publish/issues/665 to get better stack traces :)

+1 to potentially a few more retries and exponential backoff.

**Comment by AbhiPrasad** [comment]
Closing because this is pretty stale. We can re-open and revisit this later.
