### ISSUE TITLE
Revision option for prepare

### ISSUE THREAD

**Issue by Jean85** [getsentry/craft#34]
Hi! It would be nice to add the `--rev` option for the `prepare` command, is it possible?

**Comment by tonyo** [comment]
What would be the semantics of `prepare` with `rev` provided?
Do you want to create the release branch based on that revision?

**Comment by Jean85** [comment]
Yes, exactly. I needed that today here: https://github.com/getsentry/sentry-symfony/pull/283
Master was already ahead (3.3.x, new minor version) and I needed to release a patch (3.2.1) using 
8a176d7 as a revision, before merging master in that branch.

`craft release --rev` is able to do that, but I do not have enough permission, so @HazAT had to do that for me, without my help and review beforehand with `craft prepare`.

**Comment by tonyo** [comment]
Just to clarify: as far as I understand, the agreement here was that `release` would be run by @HazAT anyway, so adding new features to `prepare` will not really fix it.

Regarding the feature itself, generally I agree that it'd make sense to add it.
To agree on the semantics, `craft prepare --rev REV VERSION` will do the following:
* Checkout REV
* Check that the changelog for the new version (VERSION) is there (if the changelog check is configured)
* Create a new release branch 
* Run pre-release command (which is user-configured, it usually bumps the version in some files, and you can run some additional checks there) and commit the changes
* Push the release branch

Does it sound good?

**Comment by Jean85** [comment]
Yes, absolutely!
