### ISSUE TITLE
Refuse unknown flags

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/craft#38]
It would be cool if `craft` failed when passed unknown flags.

At the moment, it seems that unknown flags are ignored, which can hide typos (or flags that changed across `craft` versions?!).

Example:

```console
$ craft publish X.X.X --skip-status-check
```

Ignores the flag and tries to publish a release _with_ status check. The correct flag would have been `--no-status-check`.

**Comment by tonyo** [comment]
We have the strict option validation mode on, but there's a bug in yargs: https://github.com/yargs/yargs/issues/1039
We can try to upgrade yargs to fix this.
