### ISSUE TITLE
Craft gets stuck while uploading GH artifacts

### ISSUE THREAD

**Issue by jan-auer** [getsentry/craft#384]
The publish action on sentry-native frequently gets stuck while uploading assets to GitHub. The last logs read (terminating with cancellation or timeout):

```
[info] [[target/github]] Git tag: "0.4.17"
[debug] POST /repos/getsentry/sentry-native/releases - 201 in 346ms
- Uploading asset "sentry-native.zip" to getsentry/sentry-native:0.4.17
[debug] POST /repos/getsentry/sentry-native/releases/65043191/assets?name=sentry-native.zip& - 500 in 231ms
Error: The operation was canceled.
```

Note the status code `500` response from the upload. Assuming we can trust the logs from GitHub Actions, there's something that keeps craft running in this state rather than retrying/failing.

**Comment by asottile-sentry** [comment]
I believe this was resolved by #398
