### ISSUE TITLE
Switch maven target from using maven to gradle as build system

### ISSUE THREAD

**Issue by romtsn** [getsentry/craft#404]
Maven publishing plugin lacks functionality and does not publish Gradle's and Kotlin's metadata. Gradle's publishing plugin has everything working out of the box, so we could use that instead, to have all artifacts published correctly.

For example, this is how the sentry-android artifacts look vs how sqldelight (a kotlin multiplatform lib) looks
https://repo.maven.apache.org/maven2/io/sentry/sentry-android/6.1.4/
https://repo.maven.apache.org/maven2/app/cash/sqldelight/runtime/2.0.0-alpha03/

notice how `kotlin-tooling-metadata.json` and `.module` artifacts are missing. They are not mandatory, but may become useful in the future, or if we are gonna use some Gradle's feature like dependency constraints, which is bundled within .module metadata.

**Comment by marandaneto** [comment]
This should address this issue tho https://github.com/getsentry/craft/pull/412

**Comment by romtsn** [comment]
We've decided to not do that, and rather adapt our current publishing workflow to include the aforementioned files using maven instead of switching to gradle.
