### ISSUE TITLE
Release failed merging back into main but worked

### ISSUE THREAD

**Issue by adinauer** [getsentry/craft#421]
It managed to merge the release branch into `main` but failed the build in a post step stating it's already on `main`.

### Environment

Release build for SAGP ()

### Steps to Reproduce

Performed a release (https://github.com/getsentry/publish/issues/1446)

### Expected Result

Successful build ;-)

### Actual Result

Failed release: https://github.com/getsentry/publish/actions/runs/3225479213/jobs/5277837970

```
[debug] Merging release/3.2.0 into: main
[debug] Deleting the release branch: release/3.2.0
[info] Removed the remote branch: "release/3.2.0"
[success] Version 3.2.0 has been published!
[info] Running the post-release command...
Error:  Process "/bin/bash" errored with code 1

STDOUT: /bin/bash: Your branch is up to date with 'origin/main'.
/bin/bash: 


STDERR:/bin/bash: Already on 'main'
/bin/bash: 

  
  STDOUT: /bin/bash: Your branch is up to date with 'origin/main'.
  /bin/bash:
  
  
  STDERR:/bin/bash: Already on 'main'
  /bin/bash:
  
  at HJe (/usr/local/bin/craft:550:3237)
  at p (/usr/local/bin/craft:554:467)
  at ChildProcess.<anonymous> (/usr/local/bin/craft:554:762)
  at ChildProcess.emit (events.js:400:28)
  at ChildProcess.emit (domain.js:475:12)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
```

**Comment by asottile-sentry** [comment]
those errors come from *your* post-release script, not from craft -- https://github.com/getsentry/sentry-android-gradle-plugin/blob/main/scripts/post-release.sh

**Comment by adinauer** [comment]
Thanks @asottile-sentry , do you have any hint why this might start failing now? There hasn't been any changes to the file since March.

It worked fine on the last release: https://github.com/getsentry/publish/issues/1428
Log: https://github.com/getsentry/publish/actions/runs/3195177089/jobs/5215530416

**Comment by asottile-sentry** [comment]
no idea -- maybe try adding `set -x` to the script to see where it's failing? -- the messages in the output above seem non-fatal

**Comment by adinauer** [comment]
OK nevermind then. We can make the script more robust. Just wanted to see if you know of any changes in craft causing this.
