### ISSUE TITLE
registry target: batch updates if there are multiple packages to release

### ISSUE THREAD

**Issue by tonyo** [getsentry/craft#48]
Case in question:
https://github.com/getsentry/sentry-dotnet/blob/master/.craft.yml#L11-L30

Ideally, there should be a way to batch those changes into one push to release-registry.

**Comment by bruno-garcia** [comment]
More context: One downside of the current approach is that we end up releasing the registry with unmatching versions for monorepos. Which could lead a user to install incompatible versions.

![image](https://user-images.githubusercontent.com/1633368/110006332-81172780-7ce7-11eb-9532-c9f5a2f884b6.png)


A less impactful side effect of how it currently works is that it ends up triggering lots of notifications/updates on feeds.

Some examples of usages:

https://github.com/getsentry/sentry-dotnet/blob/64d4b36002e179464231189f709e98dee087d822/.craft.yml#L13-L44

https://github.com/getsentry/sentry-java/blob/2bfdba862b97f1a1dc62e494d9309579b28466b7/.craft.yml#L12-L59
