### ISSUE TITLE
Publishing Rust packages to PyPi fails because of twine

### ISSUE THREAD

**Issue by loewenheim** [getsentry/craft#489]
### Environment

https://github.com/getsentry/publish

### Steps to Reproduce

1. Used the `release` action in `symbolic`/`sentry-cli` to release new versions
2. @ashwoods accepted the publish runs in https://github.com/getsentry/publish

### Expected Result

New versions are successfully published

### Actual Result

Both publish runs failed with errors from `twine`, although the packages are actually published on PyPi:

`sentry-cli` 2.20.6: https://github.com/getsentry/publish/actions/runs/6036766083/job/16379687491
`symbolic` 12.4.0: https://github.com/getsentry/publish/actions/runs/6096157200/job/16541149246

**Comment by asottile-sentry** [comment]
"Connection reset by peer" looks like an intermittent failure -- 2.20.5 succeeded with roughly the same binaries

I suspect this is pypi network flakiness and there's not really anything we can do about this unfortunately -- https://github.com/pypa/twine/issues/910#issuecomment-1167740715

**Comment by ashwoods** [comment]
@asottile-sentry Could we consider using "--skip-present" flag, or how should we deal with partially successful uploads?

**Comment by asottile-sentry** [comment]
craft targets are by design not idempotent to prevent accidental republish of existing versions.  in an exceptional situation like this it is better to publish a brand new version or have an administrator manually tick the boxes if it was truly sucessful
