### ISSUE TITLE
Add config for latest tagging branches

### ISSUE THREAD

**Issue by mydea** [getsentry/craft#498]
## Problem

When publishing backported versions, they are auto-set as latest in various targets (npm, github, possibly others). This means that you either need to take manual steps _or_ have to follow up with a release of the "actual" latest, which is far from ideal. 

For npm, you can circumenvent this by putting something like this on the backported branchs package.json:

```json
"publishConfig": {
  "tag": "v1"
}
```

For github, there is no way to do that (and e.g. Homebrew depends on this)

## Proposed solution

We propose to add a new top level config to allow to opt-in to define a list of target branches that should get the latest tag:

```yaml
# .craft.yml
minVersion: '0.23.1'
changelogPolicy: simple
latestTargetBranches: 
  - master
```

If this is configured, craft targets should only add the `latest` tag (or similar behavior, depending on the target) when merging into one of the defined branches.

With this, projects can opt-in to only release as `latest` when merging into e.g. master/main branch, and when merging into e.g. a `1.x` branch we can ensure to not mark this release as latest.

**Comment by BYK** [comment]
Craft already knows about the "default" branch so it feels more appropriate to make this the default behavior?

Fir backwards compatibility, you can internally enable this only for config files setting a minVersion above the change date.

**Comment by mydea** [comment]
Sounds good to me too!

So basically you mean:

* Only tag with latest if merging into the "default" branch
* Only do this if minVersion > version we introduced this

**Comment by mydea** [comment]
Actually, we just thought about this and this will not necessarily work - as the default branch is not necessarily the branch where you run releases from.

Concretely, in sentry-javascript the default branch is develop, but we release from/to the master branch (we use gitflow and still merge into develop while a release is pending etc). So for cases like these you'd still need to configure this.

We can still do both I guess, do this by default for the default branch, but allow to configure/overwrite this if needed?

**Comment by BYK** [comment]
>Concretely, in sentry-javascript the default branch is develop, but we release from/to the master branch (we use gitflow and still merge into develop while a release is pending etc). So for cases like these you'd still need to configure this.

Ah, that's quite unfortunate (and unexpected for me) 😅 

>We can still do both I guess, do this by default for the default branch, but allow to configure/overwrite this if needed?

I'd say yes but I feel like it may complicate things unnecessarily if you were looking to get this out of the door quickly. Use your own judgement then :) For the given scenario, your initial proposal makes sense to me and easy and harmless enough to start with.
