### ISSUE TITLE
Feature Request: Check out master after publish

### ISSUE THREAD

**Issue by jan-auer** [getsentry/craft#5]
When I run `craft release`, the tool creates a branch locally and pushes it to the remote. However, there is no reason to keep this branch locally (other than troubleshooting). So at least during publish, it would be great if craft could detect that the branch is still checked out go back to master.

I'm also thinking if it might make sense to check out master right away after `craft release` ran.

**Comment by tonyo** [comment]
We can switch to master after `craft release` has finished successfully, but I'm a bit hesitant to make `publish` more git-aware than it currently is. At the moment `publish` doesn't actually need to know that it is started inside a git repo, it just needs access to `.craft.yml`.

**Comment by jan-auer** [comment]
Then let's do it during `release` 👍

**Comment by tonyo** [comment]
Added in https://github.com/getsentry/craft/commit/98a58d604b3217470c736e91a0872f1329e25db2
