### ISSUE TITLE
What about Calver?

### ISSUE THREAD

**Issue by romanr** [getsentry/craft#508]
It doesn't mention version format, does it support Calver? 
Sentry is [famous for supporting Calver](https://blog.sentry.io/self-hosted-sentry-switching-to-calver/). And because of that Calver support is implied, so it doesn't have to be mentioned?

**Comment by asottile-sentry** [comment]
craft doesn't care about what strategy you use to version -- you specify the new version as an input to [craft prepare](https://github.com/getsentry/craft#craft-prepare-preparing-a-new-release)

**Comment by asottile-sentry** [comment]
full disclosure: I would not recommend using craft for new projects -- we're looking into ways to migrate off of our usage internally
