### ISSUE TITLE
Twine errors when releasing Sentry CLI to PyPI

### ISSUE THREAD

**Issue by szokeasaurusrex** [getsentry/craft#529]
### Steps to Reproduce

Attempt to release a version of the Sentry CLI (with PyPI releases enabled) in getsentry/publish. 

### Expected Result

The release (including to PyPI) succeeds.

### Actual Result

The release fails due to an [error in Twine](https://github.com/getsentry/publish/actions/runs/8437326194/job/23106871689#step:11:814).

We currently workaround this issue by disabling Python releases in the CLI (https://github.com/getsentry/sentry-cli/pull/2000). This workaround is not ideal, as we use the Python CLI releases in Sentry. Therefore, it is imperative that we resolve this problem in Craft as soon as possible.

**Comment by asottile-sentry** [comment]
I believe I fixed this with #530
