### ISSUE TITLE
Allow skipping optionally marked targets

### ISSUE THREAD

**Issue by andreiborza** [getsentry/craft#537]
Currently, it's possible to skip publishing packages by ticking checkboxes in the [publish issue](https://github.com/getsentry/publish/issues/3869), but that is a privilege only extended to repo admins.

The frontend web sdk team publishes the AWS Lambda layer for node and due to the nature of Lamda layer versioning, would like to skip publishing altogether at certain times (e.g. for preview releases). 

We were thinking of having a flag `skipPreviewReleases: boolean` available on targets in `.craft.yml` to skip publishing such targets.

**Comment by BYK** [comment]
It's not clear what you're asking for. Can you please clarify?

Here's what I understand (generalized fashion):

1. You have a lot of targets to publish
2. You want to skip certain targets __sometimes__

To be able to implement this in a generic way I think we need to understand:

1. What do you mean by skipping preview versions? What's a preview version and why is it okay to publish on some but not others? Can this be added to AWS lambda target logic directly?
2. Is it not possible to split the repo into subfolders where one is specific to AWS lambda target? I think the Ruby SDK repo did this.

**Comment by andreiborza** [comment]
Thank you for the quick reply :)

Your understanding is correct, we have many targets to publish (e.g. node, bun, express, aws lambda layer, ...) and we would like to skip releasing some of these sometimes.

Upon further discussion with the team we discovered that we're already handling the case of [skipping preview releases here](https://github.com/getsentry/craft/blob/532b8d1950b351a4ca66f825ab906238a1cbf563/src/targets/awsLambdaLayer.ts#L196-L209) for reference.

This seems overall like a better approach than introducing a flag in `.craft.yml` that we might forget to flip.

Thank you again!

**Comment by BYK** [comment]
Heh, so it indeed is being handled in the AWS Lambda target, nice!

No worries 🙂
