### ISSUE TITLE
Craft does not correctly push multi arch images

### ISSUE THREAD

**Issue by Dav1dde** [getsentry/craft#541]
### Environment

Running in Relay CI

### Steps to Reproduce

Relay has a [craft config](https://github.com/getsentry/relay/blob/master/.craft.yml#L25-L29) which pushes docker containers. The source container is a multi arch container, the pushed container is not.

### Expected Result

Craft should copy the multi arch container correctly.

### Actual Result

The container is for a single arch. See also: https://github.com/getsentry/relay/issues/3731

**Comment by BYK** [comment]
Sounds like we need a `platforms` config option for the `docker` target?

**Comment by Dav1dde** [comment]
The problem with multiarch images is, you need to build the manifest once and cant incrementally push single archs.
Which means a platforms option is most likely not going to work.

In Relay CI we use [regctl](https://github.com/regclient/regclient/) to move/copy multiarch images, this would be a simple option and could be gated behind a `multiarch: true` option, to not always require the dependeny.

The alternative I believe is to rebuild the multiarch manifest with `docker buildx imagetools`, which still seems to be very experimental.
