### ISSUE TITLE
Support monorepos with independently versioned members

### ISSUE THREAD

**Issue by Swatinem** [getsentry/craft#77]
I would like to have multiple packages/crates in a monorepo/workspace, but version and release them independently.

Ideally, craft would know about those packages, to bump their own versions individually (#76) and publish them from their respective directory.

Considering git tags, one inspiration might be [rollup/plugins](https://github.com/rollup/plugins#publishing), which uses `<pkgname>-v<version>` as the tag.

**Comment by BYK** [comment]
@Swatinem [sentry-ruby](https://github.com/getsentry/sentry-ruby/) has a similar setup and it seems to work. That said each release needs to be triggered manually.

I don't think making Craft detect all subprojects and run under them one by one is a feature we'd want to maintain or support as the return on investment is quite low. So I'll go ahead and close this issue.

Will reopen if you have other ideas or feel strongly about this.
